### ISSUE TITLE
x is not finite error quality armory vehicules

### ISSUE THREAD

**Issue by Cookeyyyy** [ZombieStriker/QualityArmory#146]
There's an error that's spamming console with quality armory vehicules

The server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

here's the spammed error :

[14:40:50] [Server thread/WARN]: [QualityArmoryVehicles2] Task #22471 for QualityArmoryVehicles2 v2.0.4 generated an exception
java.lang.IllegalArgumentException: x not finite
	at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.util.Vector.checkFinite(Vector.java:814) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.setVelocity(CraftEntity.java:426) ~[patched_1.16.5.jar:git-Purpur-1171]
	at me.zombie_striker.qav.vehicles.AbstractVehicle.basicDirections(AbstractVehicle.java:402) ~[?:?]
	at me.zombie_striker.qav.vehicles.AbstractPlane.tick(AbstractPlane.java:81) ~[?:?]
	at me.zombie_striker.qav.VehicleEntity.tick(VehicleEntity.java:155) ~[?:?]
	at me.zombie_striker.qav.Main$1.run(Main.java:194) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Lorenzo0111** [comment]
What vehicle are you using?

**Comment by Lorenzo0111** [comment]
This is the wrong repo, please use [ZombieStriker/QualityArmoryVehicles2](https://github.com/ZombieStriker/QualityArmoryVehicles2)
