### ISSUE TITLE
Creation of a new flag to deny the release of weapons in certain zones.

### ISSUE THREAD

**Issue by GeRmAnAnToNiO124** [ZombieStriker/QualityArmory#188]
It is more than that, create a flag for the areas that are as spawn or places without pvp to stop using weapons as they generate noise and disrupt certain areas, this would help a lot to the roleplay servers.

**Comment by Lorenzo0111** [comment]
There is already an addon for that: https://www.spigotmc.org/resources/qualityarmory-worldguard-addon.96868/

**Comment by GeRmAnAnToNiO124** [comment]
[06:22:40] [Server thread/INFO]: [QAWorldGuard] Enabling QAWorldGuard v1.0
[06:22:40] [Server thread/ERROR]: Error occurred while enabling QAWorldGuard v1.0 (Is it up to date?)
java.lang.IllegalStateException: New flags cannot be registered at this time
	at com.sk89q.worldguard.protection.flags.registry.SimpleFlagRegistry.register(SimpleFlagRegistry.java:60) ~[worldguard-bukkit-7.0.6-beta1-dist.jar:?]
	at me.lorenzo0111.qa.worldguard.QAWorldGuard.onEnable(QAWorldGuard.java:28) ~[QAWorldGuard.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Airplane-87]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Airplane-87]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Airplane-87]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[patched_1.17.1.jar:git-Airplane-87]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[patched_1.17.1.jar:git-Airplane-87]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725) ~[patched_1.17.1.jar:git-Airplane-87]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:308) ~[patched_1.17.1.jar:git-Airplane-87]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Airplane-87]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-87]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[06:22:40] [Server thread/INFO]: [QAWorldGuard] Disabling QAWorldGuard v1.0

dont works on 1.17 


[06:28:38 INFO]: WorldGuard 7.0.6-beta1
[06:28:38 INFO]: http://www.enginehub.org
[06:28:38 INFO]: ----------- Platforms -----------
[06:28:38 INFO]: * Bukkit-Official (7.0.6-beta1+0b66f3e)
[06:28:49 INFO]: [QualityArmory] This server is using version 2.0.2 of QualityArmory
