### ISSUE TITLE
1.8.8 Asynchronous player kick!

### ISSUE THREAD

**Issue by Atomiz2002** [ZombieStriker/QualityArmory#234]
Chronologically on console:

1. [ERROR]: [QualityArmory] Plugin QualityArmory v2.0.4 has failed to register events for class me.zombie_striker.qg.handlers.Update19Events because org/bukkit/event/player/PlayerSwapHandItemsEvent does not exist.

2. [ERROR]: Could not pass event PlayerQuitEvent to QualityArmory v2.0.4
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.getItemInMainHand()Lorg/bukkit/inventory/ItemStack;
	at me.zombie_striker.qg.listener.QAListener.onQuit(QAListener.java:960) ~[?:?]

3. [ERROR]: Could not pass event PlayerResourcePackStatusEvent to QualityArmory v2.0.4
Caused by: java.lang.IllegalStateException: Asynchronous player kick!
	at me.zombie_striker.qg.handlers.Update19resourcepackhandler.onResourcepackStatusEvent(Update19resourcepackhandler.java:19) ~[?:?]

Consider using a scheduler to synchronize the kick.

**Comment by Lorenzo0111** [comment]
I’ll try to fix it, also remember that QualityArmory does not officially support 1.8

**Comment by Atomiz2002** [comment]
thanks, and yes i know but hopefuly it isnt a huge bug to handle
