### ISSUE TITLE
[Bug]: WorldGuard Bug

### ISSUE THREAD

**Issue by GeRmAnAnToNiO124** [ZombieStriker/QualityArmory#261]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

[05:28:50 ERROR]: Could not pass event PlayerInteractEvent to QualityArmory v2.0.5.1
java.lang.ClassCastException: class java.util.Optional cannot be cast to class me.zombie_striker.qg.hooks.protection.worldguard.flag.WrappedState (java.util.Optional is in module java.base of loader 'bootstrap'; me.zombie_striker.qg.hooks.protection.worldguard.flag.WrappedState is in unnamed module of loader 'QualityArmory (3).jar' @29ebbdf4)
        at me.zombie_striker.qg.hooks.protection.implementation.WorldGuardHook.canPvp(WorldGuardHook.java:39) ~[QualityArmory (3).jar:?]
        at me.zombie_striker.qg.hooks.protection.ProtectionHandler.lambda$canPvp$1(ProtectionHandler.java:37) ~[QualityArmory (3).jar:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1715) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637) ~[?:?]
        at me.zombie_striker.qg.hooks.protection.ProtectionHandler.canPvp(ProtectionHandler.java:37) ~[QualityArmory (3).jar:?]
        at me.zombie_striker.qg.api.QualityArmory.allowGunsInRegion(QualityArmory.java:153) ~[QualityArmory (3).jar:?]
        at me.zombie_striker.qg.guns.utils.GunUtil.shootInstantVector(GunUtil.java:184) ~[QualityArmory (3).jar:?]
        at me.zombie_striker.qg.guns.utils.GunUtil.shootHandler(GunUtil.java:63) ~[QualityArmory (3).jar:?]
        at me.zombie_striker.qg.guns.utils.GunUtil.shootHandler(GunUtil.java:49) ~[QualityArmory (3).jar:?]
        at me.zombie_striker.qg.guns.utils.GunUtil.basicShoot(GunUtil.java:483) ~[QualityArmory (3).jar:?]
        at me.zombie_striker.qg.guns.utils.GunUtil.basicShoot(GunUtil.java:446) ~[QualityArmory (3).jar:?]
        at me.zombie_striker.qg.guns.Gun.USE_THIS_INSTEAD_OF_INDEVIDUAL_SHOOT_METHODS(Gun.java:154) ~[QualityArmory (3).jar:?]
        at me.zombie_striker.qg.guns.Gun.shoot(Gun.java:547) ~[QualityArmory (3).jar:?]
        at me.zombie_striker.qg.guns.Gun.onClick(Gun.java:927) ~[QualityArmory (3).jar:?]
        at me.zombie_striker.qg.guns.Gun.onLMB(Gun.java:768) ~[QualityArmory (3).jar:?]
        at me.zombie_striker.qg.listener.QAListener.onClick(QAListener.java:906) ~[QualityArmory (3).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor938.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Airplane-112]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Airplane-112]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Airplane-112]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Airplane-112]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543) ~[patched_1.17.1.jar:git-Airplane-112]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:506) ~[patched_1.17.1.jar:git-Airplane-112]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:501) ~[patched_1.17.1.jar:git-Airplane-112]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAnimate(ServerGamePacketListenerImpl.java:2300) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:25) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:7) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-112]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[05:28:50 INFO]: UUID of player cheviananashe is 572925c6-5887-4269-868d-24e3cf3caee3
[05:28:50 INFO]: cheviananashe[/190.5.42.234:34049] logged in with entity id 565198 at ([tierra]-8724.899146005226, 69.0, 4550.351472967726)

### Expected Behaviour

Run without errors and Guns works on this specific region

### Server Version

1.17.1

**Comment by DextralityNetwork** [comment]
The bug persist

**Comment by Lorenzo0111** [comment]
I still didn’t released it

**Comment by Lorenzo0111** [comment]
I’ll try to release it today
