### ISSUE TITLE
Plugin is not working after new update of Craftbukkit

### ISSUE THREAD

**Issue by PetrusTryb** [ZombieStriker/QualityArmory#27]
When I try to enable it, it throws an exception:
Error occurred while enabling QualityArmory v1.1.135 (Is it up to date?)
java.lang.NullPointerException: null
at me.zombie_striker.qg.QAMain.onEnable(QAMain.java:383) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[Craftbukkit-1.13.2.jar:git-Bukkit-f40143e]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [Craftbukkit-1.13.2.jar:git-Bukkit-f40143e]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:409) [Craftbukkit-1.13.2.jar:git-Bukkit-f40143e]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:423) [Craftbukkit-1.13.2.jar:git-Bukkit-f40143e]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:349) [Craftbukkit-1.13.2.jar:git-Bukkit-f40143e]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:571) [Craftbukkit-1.13.2.jar:git-Bukkit-f40143e]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:533) [Craftbukkit-1.13.2.jar:git-Bukkit-f40143e]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:411) [Craftbukkit-1.13.2.jar:git-Bukkit-f40143e]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:270) [Craftbukkit-1.13.2.jar:git-Bukkit-f40143e]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:676) [Craftbukkit-1.13.2.jar:git-Bukkit-f40143e]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_45] 

I can open the /qa craft, but I cannot buy anything and shoot.

**Comment by PetrusTryb** [comment]
Sorry, It is a problem with **Citizens2** on my server, not with Quality Armory.
