### ISSUE TITLE
[Bug]: Could not pass event PlayerInteractEvent to QualityArmory v2.0.5.1

### ISSUE THREAD

**Issue by StonFlip** [ZombieStriker/QualityArmory#271]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

I configured the plugin for myself and made a mistake somewhere and now the weapon does not shoot

### Expected Behaviour

Before I set up the plugin everything worked

### Plugins

AdvancedBan, AuthMe, Chatty, ChestCommands*, Citizens, ClearLag, CMILib, CoreProtect, CraftHeads, dynmap, Dynmap-Meets-Towny, Economy, Essentials, EssentialsChat, EssentialsSpawn, HolographicDisplays, Jobs, LuckPerms, Negativity, PlaceholderAPI, PvPManager, QualityArmory, SkinsRestorer, TAB, Towny, TownyChat, TownyFlight, Vault, WorldBorder, WorldEdit, WorldGuard

### Server Version

1.16.5 Paper

### Relevant log output

```shell
[20:33:18 ERROR]: Could not pass event PlayerInteractEvent to QualityArmory v2.0.5.1
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:662) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]
        at me.zombie_striker.qg.guns.Gun.getAmount(Gun.java:165) ~[?:?]
        at me.zombie_striker.qg.guns.Gun.onClick(Gun.java:882) ~[?:?]
        at me.zombie_striker.qg.guns.Gun.onLMB(Gun.java:768) ~[?:?]
        at me.zombie_striker.qg.listener.QAListener.onClick(QAListener.java:906) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor605.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-790]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-790]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-790]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-790]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[patched_1.16.5.jar:git-Paper-790]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:512) ~[patched_1.16.5.jar:git-Paper-790]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507) ~[patched_1.16.5.jar:git-Paper-790]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2223) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:29) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:8) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-790]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by Lorenzo0111** [comment]
Please send your configuration file

**Comment by StonFlip** [comment]
ENABLE-DEBUG: false                                                  
language: en                                                         
FriendlyFireEnabled: true                                            
KickPlayerIfDeniedResourcepack: false                                
useDefaultResourcepack: true                                         
EnableWeaponDurability: false                                        
BulletDetection:                                                     
  step: 0.1                                                          
BlockBullets:                                                        
  door: false                                                        
  halfslabs: false                                                   
  leaves: false                                                      
  water: false                                                       
  glass: false                                                       
enableInteract:                                                      
  Chests: true                                                       
overrideAnvil: false                                                 
showPossibleCrashHelpMessage: true                                   
verboseItemLogging: false                                            
enable_permssionsToShoot: false                                      
sendOnJoin: true                                                     
sendTitleOnJoin: false                                               
SecondsTillRPIsSent: 5.0                                             
enableBulletTrails: true                                             
BulletTrailsSpacing: 0.5                                             
enableIgnoreArmorProtection: false                                   
enableIgnoreUnbreakingChecks: false                                  
enableIgnoreSkipForBasegameItems: false                              
Items:                                                               
  enable_Unbreaking: true                                            
enableReloadingOnDrop: false                                         
enableReloadingWhenSwapToOffhand: true                               
enableReloadOnlyWhenSwapToOffhand: false                             
allowGunHitEntities: true                                            
showOutOfAmmoOnTitle: false                                          
showReloadingTitle: false                                            
showAmmoInXPBar: false                                               
enableExplosionDamage: false                                         
enableExplosionDamageDrop: false                                     
enablePrimaryWeaponLimiter: false                                    
weaponlimiter_primaries: 2                                           
weaponlimiter_secondaries: 2                                         
enableCrafting: false                                                
enableShop: true                                                     
AUTO-UPDATE: true                                                    
Swap-Reload-and-Shooting-Controls: false                             
Order-Shop-By-Price: false

**Comment by StonFlip** [comment]
Resetting the newguns folder helped me
