### ISSUE TITLE
[Bug]: java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by h266579110** [ZombieStriker/QualityArmory#281]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Shooting will cause server WARN log
M1 Garand, AK47, Minigun, M40, fames, M16, MP40... etc

ProtocolLib using dev build #540

### Expected Behaviour

no error

### Server Version

Paper 1.18.1 - 187

### Relevant log output

```shell
[23:08:11 WARN] java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getOrCreateTag()
[23:08:11 WARN] at java.base/java.lang.Class.getMethod(Class.java:2227)
[23:08:11 WARN] at QualityArmory.jar//me.zombie_striker.qg.handlers.ProtocolLibHandler$2.onPacketSending(ProtocolLibHandler.java:128)
[23:08:11 WARN] at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[23:08:11 WARN] at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[23:08:11 WARN] at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
[23:08:11 WARN] at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
[23:08:11 WARN] at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346)
[23:08:11 WARN] at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308)
[23:08:11 WARN] at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436)
[23:08:11 WARN] at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72)
[23:08:11 WARN] at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376)
[23:08:11 WARN] at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346)
[23:08:11 WARN] at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[23:08:11 WARN] at ProtocolLib.jar//com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[23:08:11 WARN] at net.minecraft.network.NetworkManager.writePacket(NetworkManager.java:401)
[23:08:11 WARN] at net.minecraft.network.NetworkManager.a(NetworkManager.java:348)
[23:08:11 WARN] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2026)
[23:08:11 WARN] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2012)
[23:08:11 WARN] at net.minecraft.server.level.PlayerChunkMap$EntityTracker.a(PlayerChunkMap.java:2296)
[23:08:11 WARN] at net.minecraft.server.level.PlayerChunkMap.a(PlayerChunkMap.java:2118)
[23:08:11 WARN] at net.minecraft.server.level.ChunkProviderServer.b(ChunkProviderServer.java:1176)
[23:08:11 WARN] at net.minecraft.world.entity.EntityLiving.b(EntityLiving.java:3081)
[23:08:11 WARN] at net.minecraft.world.entity.EntityLiving.x(EntityLiving.java:2993)
[23:08:11 WARN] at net.minecraft.world.entity.EntityLiving.k(EntityLiving.java:2895)
[23:08:11 WARN] at net.minecraft.world.entity.player.EntityHuman.k(EntityHuman.java:268)
[23:08:11 WARN] at net.minecraft.server.level.EntityPlayer.l(EntityPlayer.java:669)
[23:08:11 WARN] at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:317)
[23:08:11 WARN] at net.minecraft.network.NetworkManager.a(NetworkManager.java:526)
[23:08:11 WARN] at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:201)
[23:08:11 WARN] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1636)
[23:08:11 WARN] at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[23:08:11 WARN] at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[23:08:11 WARN] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[23:08:11 WARN] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[23:08:11 WARN] at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Lorenzo0111** [comment]
Are you sure you are using the latest version?

**Comment by h266579110** [comment]
> Are you sure you are using the latest version?

Yes, im using your dev build.
