### ISSUE TITLE
[Bug]:error

### ISSUE THREAD

**Issue by ddman1211** [ZombieStriker/QualityArmory#285]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

[22:44:34 ERROR]: Error occurred while enabling QualityArmory v2.0.5.1 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant me.zombie_striker.qg.guns.utils.WeaponType.SSEMIR
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at me.zombie_striker.qg.guns.utils.WeaponType.valueOf(WeaponType.java:3) ~[?:?]
        at me.zombie_striker.qg.config.GunYMLLoader.loadGuns(GunYMLLoader.java:288) ~[?:?]
        at me.zombie_striker.qg.config.GunYMLLoader.loadGuns(GunYMLLoader.java:490) ~[?:?]
        at me.zombie_striker.qg.QAMain.reloadVals(QAMain.java:1150) ~[?:?]
        at me.zombie_striker.qg.QAMain.onEnable(QAMain.java:661) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]

### Expected Behaviour

[22:44:34 ERROR]: Error occurred while enabling QualityArmory v2.0.5.1 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant me.zombie_striker.qg.guns.utils.WeaponType.SSEMIR
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at me.zombie_striker.qg.guns.utils.WeaponType.valueOf(WeaponType.java:3) ~[?:?]
        at me.zombie_striker.qg.config.GunYMLLoader.loadGuns(GunYMLLoader.java:288) ~[?:?]
        at me.zombie_striker.qg.config.GunYMLLoader.loadGuns(GunYMLLoader.java:490) ~[?:?]
        at me.zombie_striker.qg.QAMain.reloadVals(QAMain.java:1150) ~[?:?]
        at me.zombie_striker.qg.QAMain.onEnable(QAMain.java:661) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]

### Plugins

AdvancedKits, AlonsoTags, Citizens, ComplexTurrets, CustomCrafting, DeluxeCombat, DungeonSystem, EliteBosses, EnchantmentForge, EpicCraftingsPlus, Essentials, EssentialsSpawn, ExecutableBlocks, ExecutableItems, HeadDatabase, Interactions, InventorySaver, iShop, Machines, MTVehicles, NBTAPI, PowerCamera, ProtocolLib, PyroFishingPro, PyroLib, PyroSpawners, QualityArmory, SCore, Vault, Vegas, ViaBackwards, ViaRewind, ViaVersion, WolfyUtilities

### Server Version

1.16.5

### Relevant log output

```shell
[22:44:34 ERROR]: Error occurred while enabling QualityArmory v2.0.5.1 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant me.zombie_striker.qg.guns.utils.WeaponType.SSEMIR
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at me.zombie_striker.qg.guns.utils.WeaponType.valueOf(WeaponType.java:3) ~[?:?]
        at me.zombie_striker.qg.config.GunYMLLoader.loadGuns(GunYMLLoader.java:288) ~[?:?]
        at me.zombie_striker.qg.config.GunYMLLoader.loadGuns(GunYMLLoader.java:490) ~[?:?]
        at me.zombie_striker.qg.QAMain.reloadVals(QAMain.java:1150) ~[?:?]
        at me.zombie_striker.qg.QAMain.onEnable(QAMain.java:661) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Lorenzo0111** [comment]
SSEMIR is not a valid weapon type
