### ISSUE TITLE
[Bug]: Console Errors with ProtocolLib

### ISSUE THREAD

**Issue by BboyZeroOne** [ZombieStriker/QualityArmory#316]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Server crashes when there is an error. Unsure what is the cause that makes it crash. Error log says its from QualityArmory

### Expected Behaviour

Should not pop up such errors.

### Plugins

ProtocolLib, QualityArmory

### Server Version

This server is running Paper version git-Paper-216 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 30cb7d0) You are running the latest version Previous version: git-Paper-399 (MC: 1.17.1)

### Relevant log output

```shell
[12:12:04 WARN]: java.lang.NoSuchMethodException: java.lang.Boolean.setBoolean(java.lang.String,boolean)
[12:12:04 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[12:12:04 WARN]:        at QualityArmory.jar//me.zombie_striker.qg.handlers.ProtocolLibHandler$2.onPacketSending(ProtocolLibHandler.java:134)
[12:12:04 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[12:12:04 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[12:12:04 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
[12:12:04 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
[12:12:04 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346)
[12:12:04 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308)
[12:12:04 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436)
[12:12:04 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72)
[12:12:04 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376)
[12:12:04 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346)
[12:12:04 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[12:12:04 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[12:12:04 WARN]:        at net.minecraft.network.NetworkManager.writePacket(NetworkManager.java:423)
[12:12:04 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:370)
[12:12:04 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2022)
[12:12:04 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2008)
[12:12:04 WARN]:        at net.minecraft.server.level.PlayerChunkMap$EntityTracker.a(PlayerChunkMap.java:2256)
[12:12:04 WARN]:        at net.minecraft.server.level.PlayerChunkMap.a(PlayerChunkMap.java:2078)
[12:12:04 WARN]:        at net.minecraft.server.level.ChunkProviderServer.b(ChunkProviderServer.java:1182)
[12:12:04 WARN]:        at net.minecraft.world.entity.EntityLiving.b(EntityLiving.java:3090)
[12:12:04 WARN]:        at net.minecraft.world.entity.EntityLiving.x(EntityLiving.java:3002)
[12:12:04 WARN]:        at net.minecraft.world.entity.EntityLiving.k(EntityLiving.java:2904)
[12:12:04 WARN]:        at net.minecraft.world.entity.player.EntityHuman.k(EntityHuman.java:268)
[12:12:04 WARN]:        at net.minecraft.server.level.EntityPlayer.l(EntityPlayer.java:669)
[12:12:04 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:314)
[12:12:04 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:555)
[12:12:04 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:201)
[12:12:04 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1646)
[12:12:04 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[12:12:04 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1480)
[12:12:04 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1273)
[12:12:04 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[12:12:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:12:10 WARN]: java.lang.NoSuchMethodException: java.lang.Boolean.setBoolean(java.lang.String,boolean)
[12:12:10 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[12:12:10 WARN]:        at QualityArmory.jar//me.zombie_striker.qg.handlers.ProtocolLibHandler$2.onPacketSending(ProtocolLibHandler.java:134)
[12:12:10 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[12:12:10 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[12:12:10 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
[12:12:10 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
[12:12:10 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346)
[12:12:10 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308)
[12:12:10 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436)
[12:12:10 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72)
[12:12:10 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376)
[12:12:10 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346)
[12:12:10 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[12:12:10 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[12:12:10 WARN]:        at net.minecraft.network.NetworkManager.writePacket(NetworkManager.java:423)
[12:12:10 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:370)
[12:12:10 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2022)
[12:12:10 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2008)
[12:12:10 WARN]:        at net.minecraft.server.level.PlayerChunkMap$EntityTracker.a(PlayerChunkMap.java:2256)
[12:12:10 WARN]:        at net.minecraft.server.level.PlayerChunkMap.a(PlayerChunkMap.java:2078)
[12:12:10 WARN]:        at net.minecraft.server.level.ChunkProviderServer.b(ChunkProviderServer.java:1182)
[12:12:10 WARN]:        at net.minecraft.world.entity.EntityLiving.b(EntityLiving.java:3090)
[12:12:10 WARN]:        at net.minecraft.world.entity.EntityLiving.x(EntityLiving.java:3002)
[12:12:10 WARN]:        at net.minecraft.world.entity.EntityLiving.k(EntityLiving.java:2904)
[12:12:10 WARN]:        at net.minecraft.world.entity.player.EntityHuman.k(EntityHuman.java:268)
[12:12:10 WARN]:        at net.minecraft.server.level.EntityPlayer.l(EntityPlayer.java:669)
[12:12:10 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:314)
[12:12:10 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:555)
[12:12:10 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:201)
[12:12:10 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1646)
[12:12:10 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[12:12:10 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1480)
[12:12:10 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1273)
[12:12:10 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[12:12:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by BboyZeroOne** [comment]
#305 has the same issue, but their logs expired. Here is my logs and reports instead.

**Comment by BboyZeroOne** [comment]
Additional Issue.

1. CZ.75 weapon uses the wrong skin.
2. There doesn't seem to be any M4PulseRifle in the newguns plugin folder.

**Comment by tskopen** [comment]
1. i have the same issue dunno why
2. have you tryed to create one? also sometimes the files are called smth different then ingame
3. mk-19 may have unlimited ammo if your in creative. 

also do you have the full logs.
also a trick ik is to make a fold called plugins old and move the issue plugins to it then load the server without them to see what plugin it is spefically.

**Comment by BboyZeroOne** [comment]
> 1. i have the same issue dunno why
> 2. have you tryed to create one? also sometimes the files are called smth different then ingame
> 3. mk-19 may have unlimited ammo if your in creative.
> 
> also do you have the full logs. also a trick ik is to make a fold called plugins old and move the issue plugins to it then load the server without them to see what plugin it is spefically.

1. I think everyone has the same issue on this, the issue is there since the first time I start up the plugin.
2. Nope, but I believe it is same as point 1.
3. Nope, I am not in creative gamemode upon testing.

Upon server startup, there doesn't seem to be any issue when loading QualityArmory. The console logs that I have shared above appeared after a few players on my server started shooting each other.

**Comment by tskopen** [comment]
it talks alot about ProtocolLib, do you have the most recent version of it?

**Comment by BboyZeroOne** [comment]
> it talks alot about ProtocolLib, do you have the most recent version of it?

Yep, based on their latest release on github.

**Comment by tskopen** [comment]
have you tryed it without any other plugins. tip, make a folder called pluginsold and move them all there until you wanna move them back

**Comment by BboyZeroOne** [comment]
> have you tryed it without any other plugins. tip, make a folder called pluginsold and move them all there until you wanna move them back

Nope, not yet. Currently I'm running on a production server and I am unable to test it yet.

**Comment by Lorenzo0111** [comment]
Can you try with [this](https://ci.codemc.io/job/ZombieStriker/job/QualityArmory/lastSuccessfulBuild/artifact/target/QualityArmory.jar) dev build?

**Comment by BboyZeroOne** [comment]
> Can you try with [this](https://ci.codemc.io/job/ZombieStriker/job/QualityArmory/lastSuccessfulBuild/artifact/target/QualityArmory.jar) dev build?

Sure! Thanks!

**Comment by BboyZeroOne** [comment]
> Additional Issue.
> 
> 1. CZ.75 weapon uses the wrong skin texture. (Its using PKP skin)
> 2. There doesn't seem to be any M41PulseRifle in the newguns plugin folder.
> 3. MK-19 seems to have unlimited ammo despite config says false.

Two more issues.
- Shooting with Minigun would constantly give you 7.62 ammo for some unknown reason, cant find it under the minigun config.
- Setting "firing_knockback:" in any weapon's config would allow players to "fly". When players aim the ground while shooting, it will give them knockback while makes them "fly".

**Comment by Lorenzo0111** [comment]
> > Additional Issue.
> 
> > 
> 
> > 1. CZ.75 weapon uses the wrong skin texture. (Its using PKP skin)
> 
> > 2. There doesn't seem to be any M41PulseRifle in the newguns plugin folder.
> 
> > 3. MK-19 seems to have unlimited ammo despite config says false.
> 
> 
> 
> Two more issues.
> 
> - Shooting with Minigun would constantly give you 7.62 ammo for some unknown reason, cant find it under the minigun config.
> 
> - Setting "firing_knockback:" in any weapon's config would allow players to "fly". When players aim the ground while shooting, it will give them knockback while makes them "fly".

Please open new issues for these bugs

**Comment by Lorenzo0111** [comment]
> > Can you try with [this](https://ci.codemc.io/job/ZombieStriker/job/QualityArmory/lastSuccessfulBuild/artifact/target/QualityArmory.jar) dev build?
> 
> 
> 
> Sure! Thanks!

Does it work?

**Comment by SideLo98** [comment]
> > > Can you try with [this](https://ci.codemc.io/job/ZombieStriker/job/QualityArmory/lastSuccessfulBuild/artifact/target/QualityArmory.jar) dev build?
> > 
> > 
> > Sure! Thanks!
> 
> Does it work?

for me it fixed the protollib spam issue in console

**Comment by Fer-Jgu** [comment]
I have the same issue );
