### ISSUE TITLE
[Bug]: Could not pass event PlayerInteractEvent to QualityArmory v2.0.8

### ISSUE THREAD

**Issue by Nagisocks** [ZombieStriker/QualityArmory#413]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

I start the server on a pufferfish 1 19 2 and for some reason the plugin does everything and displays it, but the weapon shoots arrows, and this is displayed in the console (Could not pass event PlayerInteractEvent to QualityArmory v2.0.8)

### Expected Behaviour

That the weapon will shoot bullets

### Plugins

Quality armory

### Server Version

1.19.2

### Relevant log output

```shell
[13:12:32 ERROR]: Could not pass event PlayerInteractEvent to QualityArmory v2.0.8 
java.lang.NoClassDefFoundError: de/tr7zw/nbtapi/NBTItem 
        at me.zombie_striker.qg.guns.Gun.getAmount(Gun.java:165) ~[QualityArmory.jar:?] 
        at me.zombie_striker.qg.guns.Gun.onClick(Gun.java:1032) ~[QualityArmory.jar:?] 
        at me.zombie_striker.qg.guns.Gun.onRMB(Gun.java:750) ~[QualityArmory.jar:?] 
        at me.zombie_striker.qg.listener.QAListener.onClick(QAListener.java:904) ~[QualityArmory.jar:?] 
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor9.execute(Unknown Source) ~[?:?] 
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?] 
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:git-Pufferfish-47] 
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?] 
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?] 
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[pufferfish-1.19.2.jar:git-Pufferfish-47] 
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[pufferfish-1.19.2.jar:git-Pufferfish-47] 
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497) ~[pufferfish-1.19.2.jar:git-Pufferfish-47] 
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:492) ~[pufferfish-1.19.2.jar:git-Pufferfish-47] 
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:488) ~[pufferfish-1.19.2.jar:git-Pufferfish-47] 
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2027) ~[?:?] 
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?] 
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?] 
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?] 
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.2.jar:git-Pufferfish-47] 
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?] 
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?] 
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1343) ~[pufferfish-1.19.2.jar:git-Pufferfish-47] 
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[pufferfish-1.19.2.jar:git-Pufferfish-47] 
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?] 
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1320) ~[pufferfish-1.19.2.jar:git-Pufferfish-47] 
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1313) ~[pufferfish-1.19.2.jar:git-Pufferfish-47] 
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?] 
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1291) ~[pufferfish-1.19.2.jar:git-Pufferfish-47] 
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[pufferfish-1.19.2.jar:git-Pufferfish-47] 
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-47] 
        at java.lang.Thread.run(Thread.java:1589) ~[?:?] 
Caused by: java.lang.ClassNotFoundException: de.tr7zw.nbtapi.NBTItem 
        ... 31 more
```

**Comment by Lorenzo0111** [comment]
Fixed with the latest release
