### ISSUE TITLE
qav error

### ISSUE THREAD

**Issue by DenisJ9798** [ZombieStriker/QualityArmory#44]
[04:57:27] [Server thread/INFO]: aleksey2009BRO issued server command: /QAV shop
[04:57:27] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'qav' in plugin QualityArmoryVehicles v1.0.53
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[osnova1.jar:git-Paper-1618]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[osnova1.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[osnova1.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[osnova1.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1401) ~[osnova1.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.chat(CraftPlayer.java:352) ~[osnova1.jar:git-Paper-1618]
	at com.gmail.filoghost.chestcommands.internal.icon.command.PlayerIconCommand.execute(PlayerIconCommand.java:15) ~[?:?]
	at com.gmail.filoghost.chestcommands.internal.CommandsClickHandler.onClick(CommandsClickHandler.java:34) ~[?:?]
	at com.gmail.filoghost.chestcommands.api.Icon.onClick(Icon.java:319) ~[?:?]
	at com.gmail.filoghost.chestcommands.internal.icon.ExtendedIcon.onClick(ExtendedIcon.java:243) ~[?:?]
	at com.gmail.filoghost.chestcommands.task.ExecuteCommandsTask.run(ExecuteCommandsTask.java:21) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[osnova1.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[osnova1.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[osnova1.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[osnova1.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[osnova1.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[osnova1.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 27
	at java.util.Arrays$ArrayList.set(Arrays.java:3846) ~[?:1.8.0_221]
	at net.minecraft.server.v1_12_R1.NonNullList.set(SourceFile:51) ~[osnova1.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCustom$MinecraftInventory.setItem(CraftInventoryCustom.java:107) ~[osnova1.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.setItem(CraftInventory.java:96) ~[osnova1.jar:git-Paper-1618]
	at me.zombie_striker.easygui.EasyGUI.<init>(EasyGUI.java:108) ~[?:?]
	at me.zombie_striker.easygui.EasyGUI.generateGUIIfNoneExist(EasyGUI.java:75) ~[?:?]
	at me.zombie_striker.easygui.EasyGUI.generateGUIIfNoneExist(EasyGUI.java:70) ~[?:?]
	at me.zombie_striker.qg.exp.cars.menu.MenuHandler.openShop(MenuHandler.java:236) ~[?:?]
	at me.zombie_striker.qg.exp.cars.ExpansionHandler.onCommand(ExpansionHandler.java:1224) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[osnova1.jar:git-Paper-1618]
	... 17 more

**Comment by ZombieStriker** [comment]
This will be fixed in the next update.
