### ISSUE TITLE
[23:14:33 ERROR]: Could not pass event PlayerInteractEvent to QualityArmory v2.0.10

### ISSUE THREAD

**Issue by Lorenzo0111** [ZombieStriker/QualityArmory#542]
[23:14:33 ERROR]: Could not pass event PlayerInteractEvent to QualityArmory v2.0.10
me.zombie_striker.qg.nbt.NbtApiException: [?]Error while calling the method 'contains(java.lang.String)', loaded: true, Enum: COMPOUND_HAS_KEY, Passed Class: class java.lang.Boolean
        at me.zombie_striker.qg.nbt.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:358) ~[QualityArmory.jar:?]
        at me.zombie_striker.qg.nbt.NBTReflectionUtil.getData(NBTReflectionUtil.java:635) ~[QualityArmory.jar:?]
        at me.zombie_striker.qg.nbt.NBTCompound.hasTag(NBTCompound.java:624) ~[QualityArmory.jar:?]
        at me.zombie_striker.qg.nbt.NBTCompound.hasKey(NBTCompound.java:611) ~[QualityArmory.jar:?]
        at me.zombie_striker.qg.guns.Gun.getAmount(Gun.java:169) ~[QualityArmory.jar:?]
        at me.zombie_striker.qg.guns.Gun.getAmount(Gun.java:162) ~[QualityArmory.jar:?]
        at me.zombie_striker.qg.guns.Gun.onClick(Gun.java:884) ~[QualityArmory.jar:?]
        at me.zombie_striker.qg.guns.Gun.onLMB(Gun.java:766) ~[QualityArmory.jar:?]
        at me.zombie_striker.qg.listener.QAListener.onClick(QAListener.java:901) ~[QualityArmory.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor300.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-203]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-203]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-203]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:593) ~[paper-1.20.2.jar:git-Paper-203]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:550) ~[paper-1.20.2.jar:git-Paper-203]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[paper-1.20.2.jar:git-Paper-203]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:540) ~[paper-1.20.2.jar:git-Paper-203]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAnimate(ServerGamePacketListenerImpl.java:2509) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:25) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.a(ServerboundSwingPacket.java:11) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-203]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-203]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-203]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-203]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-203]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-203]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-203]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-203]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@1e434302
        at jdk.internal.reflect.GeneratedMethodAccessor48.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at me.zombie_striker.qg.nbt.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:355) ~[QualityArmory.jar:?]
        ... 36 more

_Originally posted by @j3tus in https://github.com/ZombieStriker/QualityArmory/discussions/541_

**Comment by ExtremorGP** [comment]
I have the same problem on 1.20.2 with both the newest dev version and release.

**Comment by Lorenzo0111** [comment]
Fixed with dcbee68e8f8e068218d7f39cabc2f626d70e5ccd
