### ISSUE TITLE
[Bug]: Errors spamming console

### ISSUE THREAD

**Issue by blockutis** [ZombieStriker/QualityArmory#550]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Multiple errors are sent to console on certain events, such as PlayerItemHeldEvent, InventoryClickEvent, when holding a player skull or clicking on a player skull in the inventory.
The errors are for example "Could not pass event PlayerItemHeldEvent to QualityArmory v2.0.11" and "Could not pass event InventoryClickEvent to QualityArmory v2.0.11"

### Expected Behaviour

The plugin should not flood the console with errors

### Plugins

QualityArmory

### Server Version

This server is running Paper version git-Paper-299 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 96d5e6c)

### Relevant log output

```shell
[16:48:41 ERROR]: Could not pass event PlayerItemHeldEvent to QualityArmory v2.0.11
java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getName()'
        at me.zombie_striker.qg.handlers.SkullHandler.getURL64(SkullHandler.java:88) ~[QualityArmory-2.0.11.jar:?]
        at me.zombie_striker.customitemmanager.MaterialStorage.getMS(MaterialStorage.java:95) ~[QualityArmory-2.0.11.jar:?]
        at me.zombie_striker.customitemmanager.MaterialStorage.getMS(MaterialStorage.java:82) ~[QualityArmory-2.0.11.jar:?]
        at me.zombie_striker.qg.api.QualityArmory.isGun(QualityArmory.java:320) ~[QualityArmory-2.0.11.jar:?]
        at me.zombie_striker.qg.api.QualityArmory.isCustomItem(QualityArmory.java:254) ~[QualityArmory-2.0.11.jar:?]
        at me.zombie_striker.qg.api.QualityArmory.isCustomItem(QualityArmory.java:164) ~[QualityArmory-2.0.11.jar:?]
        at me.zombie_striker.qg.listener.QAListener.swap(QAListener.java:930) ~[QualityArmory-2.0.11.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1140.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-299]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-299]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-299]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleSetCarriedItem(ServerGamePacketListenerImpl.java:2091) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.handle(ServerboundSetCarriedItemPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.a(ServerboundSetCarriedItemPacket.java:10) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-299]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-299]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-299]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-299]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-299]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1410) ~[paper-1.20.2.jar:git-Paper-299]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-299]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-299]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:48:41 WARN]: [QualityArmory] Plugin QualityArmory v2.0.11 generated an exception while executing task 5367
java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getName()'
        at me.zombie_striker.qg.handlers.SkullHandler.getURL64(SkullHandler.java:88) ~[QualityArmory-2.0.11.jar:?]
        at me.zombie_striker.customitemmanager.MaterialStorage.getMS(MaterialStorage.java:95) ~[QualityArmory-2.0.11.jar:?]
        at me.zombie_striker.customitemmanager.MaterialStorage.getMS(MaterialStorage.java:82) ~[QualityArmory-2.0.11.jar:?]
        at me.zombie_striker.qg.api.QualityArmory.isGun(QualityArmory.java:320) ~[QualityArmory-2.0.11.jar:?]
        at me.zombie_striker.qg.api.QualityArmory.getGunInHand(QualityArmory.java:306) ~[QualityArmory-2.0.11.jar:?]
        at me.zombie_striker.qg.handlers.AimManager.run(AimManager.java:39) ~[QualityArmory-2.0.11.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-299]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.2.jar:git-Paper-299]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]


[20:30:21 ERROR]: Could not pass event InventoryClickEvent to QualityArmory v2.0.11
java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getName()'
        at me.zombie_striker.qg.handlers.SkullHandler.getURL64(SkullHandler.java:88) ~[QualityArmory-2.0.11.jar:?]
        at me.zombie_striker.customitemmanager.MaterialStorage.getMS(MaterialStorage.java:95) ~[QualityArmory-2.0.11.jar:?]
        at me.zombie_striker.qg.api.QualityArmory.isAmmo(QualityArmory.java:379) ~[QualityArmory-2.0.11.jar:?]
        at me.zombie_striker.qg.listener.QAListener.oninvClick(QAListener.java:413) ~[QualityArmory-2.0.11.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1538.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-299]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-299]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-299]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3108) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-299]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-299]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-299]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-299]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-299]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-299]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-299]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-299]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by ClayCoffee** [comment]
same
