### ISSUE TITLE
[Bug]: [19:53:07 ERROR]: Could not pass event PlayerInteractEvent to QualityArmory v2.0.11

### ISSUE THREAD

**Issue by Rylabs-Admin** [ZombieStriker/QualityArmory#560]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Firearms are able to shoot, cannot reload
Throwables appear to still work

### Expected Behaviour

Plugin was previously working yesterday, not sure what changed from today.

### Plugins

Chesthop, CoreProtect-22.2, EssentialsX-2.21.0, LuckPrems, QualityArmory 2.0.11, SilkSpawners_v2, sleep_most-5.3.1, Slimefun4, Vault

### Server Version

Mohist 1.20.2-129

### Relevant log output

```shell
[19:53:07 ERROR]: Could not pass event PlayerInteractEvent to QualityArmory v2.0.11
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[forge-1.20.2-48.1.0-universal.jar%23159!/:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge-1.20.2-48.1.0-universal.jar%23159!/:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[forge-1.20.2-48.1.0-universal.jar%23159!/:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:585) ~[forge-1.20.2-48.1.0-universal.jar%23159!/:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:554) ~[forge-1.20.2-48.1.0-universal.jar%23159!/:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:516) ~[forge-1.20.2-48.1.0-universal.jar%23159!/:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:512) ~[forge-1.20.2-48.1.0-universal.jar%23159!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1521) ~[server-1.20.2-20230921.100330-srg.jar%23154!/:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29) ~[server-1.20.2-20230921.100330-srg.jar%23154!/:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[server-1.20.2-20230921.100330-srg.jar%23154!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_292130_(PacketUtils.java:23) ~[server-1.20.2-20230921.100330-srg.jar%23154!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.2-20230921.100330-srg.jar%23154!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.2-20230921.100330-srg.jar%23154!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.2-20230921.100330-srg.jar%23154!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1028) ~[server-1.20.2-20230921.100330-srg.jar%23154!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:169) ~[server-1.20.2-20230921.100330-srg.jar%23154!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.2-20230921.100330-srg.jar%23154!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1011) ~[server-1.20.2-20230921.100330-srg.jar%23154!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1005) ~[server-1.20.2-20230921.100330-srg.jar%23154!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.2-20230921.100330-srg.jar%23154!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:991) ~[server-1.20.2-20230921.100330-srg.jar%23154!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:907) ~[server-1.20.2-20230921.100330-srg.jar%23154!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:276) ~[server-1.20.2-20230921.100330-srg.jar%23154!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getName()'
        at me.zombie_striker.qg.handlers.SkullHandler.getURL64(SkullHandler.java:88) ~[?:?]
        at me.zombie_striker.customitemmanager.MaterialStorage.getMS(MaterialStorage.java:95) ~[?:?]
        at me.zombie_striker.qg.api.QualityArmory.isAmmo(QualityArmory.java:379) ~[?:?]
        at me.zombie_striker.qg.api.QualityArmory.getAmmoInInventory(QualityArmory.java:658) ~[?:?]
        at me.zombie_striker.qg.api.QualityArmory.getAmmoInInventory(QualityArmory.java:650) ~[?:?]
        at me.zombie_striker.qg.guns.utils.GunUtil.hasAmmo(GunUtil.java:702) ~[?:?]
        at me.zombie_striker.qg.guns.Gun.onClick(Gun.java:1046) ~[?:?]
        at me.zombie_striker.qg.guns.Gun.onRMB(Gun.java:756) ~[?:?]
        at me.zombie_striker.qg.listener.QAListener.onClick(QAListener.java:904) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[forge-1.20.2-48.1.0-universal.jar%23159!/:?]
        ... 23 more
```

**Comment by Rylabs-Admin** [comment]
Not sure if this helps, this appears before the above log
[20:12:48 INFO]: [QualityArmory] [NBTAPI] Found Spigot: v1_20_R2! Trying to find NMS support
[20:12:48 INFO]: [QualityArmory] [NBTAPI] NMS support 'MC1_20_R2' loaded!
[20:12:48 INFO]: [QualityArmory] [NBTAPI] Using the plugin 'QualityArmory' to create a bStats instance!

**Comment by Lorenzo0111** [comment]
Please provide the configuration of the ammo giving that issue

**Comment by Rylabs-Admin** [comment]
I've been running the plugin on default values
Glocks that have been previously loaded can fire, but cannot reload


Config for 9mm ammo

invalid: false
name: 9mm
displayname: '&f9mm'
lore: []
id: 1
craftingRequirements:
- IRON_INGOT,0,1
- GUNPOWDER,0,1
- REDSTONE,0,1
craftingReturnAmount: 10
price: 2
maxItemStack: 50
material: PHANTOM_MEMBRANE
piercingSeverity: 0.7
lastModifiedByQA: 1704162772807
weaponsounds: bulletmedium
damage: 3
durability: 1000
