### ISSUE TITLE
Glowstone Support

### ISSUE THREAD

**Issue by tsao-chi** [ZombieStriker/QualityArmory#57]
This plugin crashes on [Glowstone](https://github.com/GlowstoneMC/Glowstone)
log:
```
00:14:16 [INFO] Enabling QualityArmory v1.1.154
00:14:16 [SEVERE] Error occurred while enabling QualityArmory v1.1.154 (Is it up to date?)
java.lang.NumberFormatException: For input string: "e"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at me.zombie_striker.qg.QAMain.isVersionHigherThan(QAMain.java:244)
	at me.zombie_striker.qg.QAMain.reloadVals(QAMain.java:982)
	at me.zombie_striker.qg.QAMain.onEnable(QAMain.java:567)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
	at net.glowstone.GlowServer.enablePlugins(GlowServer.java:1346)
	at net.glowstone.GlowServer.start(GlowServer.java:819)
	at net.glowstone.GlowServer.run(GlowServer.java:625)
	at net.glowstone.GlowServer.main(GlowServer.java:489)
00:14:16 [INFO] Disabling QualityArmory v1.1.154
```

**Comment by test414EFF** [comment]
Unfortunately, Glowstone is not yet finished. QualityArmory and other plugins written for the Bukkit API may try to access parts of the API not yet implemented into Glowstone.
